### ISSUE TITLE
How to eliminate Error when installing web3.py

### ISSUE THREAD

**Issue by EddyDomingo** [PatrickAlphaC/web3_py_simple_storage#1]
I am attempting to install web3 on my windows machine. I am using the Visual studio code terminal to do this. I have used both commands.

pip install web3
pip3 install web3
The first error I was getting was around the Visual studios build tools which I was able to install. Now when I run the command I get this error.

```
ERROR: Command errored out with exit status 1: 'C:\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\ealvarado\AppData\Local\Temp\pip-install-nfyoy3t_\cytoolz_9d52991e4515405886466c30cd8781ec\setup.py'"'"'; file='"'"'C:\Users\ealvarado\AppData\Local\Temp
<img width="663" alt="Error" src="https://user-images.githubusercontent.com/68975969/137226585-042d674f-92dc-4a24-a22f-07fa9cdac5e0.PNG">
\pip-install-nfyoy3t_\cytoolz_9d52991e4515405886466c30cd8781ec\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(file) if os.path.exists(file) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record 'C:\Users\ealvarado\AppData\Local\Temp\pip-record-g88od3fy\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Python310\Include\cytoolz' Check the logs for full command output. WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages) WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages) WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages) WARNING: You are using pip version 21.2.3; however, version 21.3 is available. You should consider upgrading via the 'C:\Python310\python.exe -m pip install --upgrade pip' command.
```

**Comment by EddyDomingo** [comment]
stackoverflow question linkl

https://stackoverflow.com/questions/69562276/how-to-eliminate-error-when-installing-web3-py

**Comment by PatrickAlphaC** [comment]
Great work making a stackoverflow question on this!

I think you were the one on twitter playing with 3.10 here... I think some of the tools might not work so well with 3.10. Were you able to get things to work with 3.9?

**Comment by xbeaulac** [comment]
I received this exact error while I took the course. To solve it, I followed [this stackoverflow](https://stackoverflow.com/questions/69054403/how-can-i-fix-this-error-installing-web3-on-python). After a lot of digging, adding the C/C++ extension to Visual Studio Code seemed to get rid of the errors!

**Comment by PatrickAlphaC** [comment]
Love the grit! Do you think we should put that post somewhere more visable? 

Closing, but looking forward to your feedback!
