### ISSUE TITLE
Incorrect Python Version Showing in Visual Studio Code

### ISSUE THREAD

**Issue by jasoncliao** [PatrickAlphaC/web3_py_simple_storage#19]
Hi there,

This may be a simple question but I have downloaded the newest version of Python 3.10.2 but when I type in "python --version" it returns "Python 2.7.16."  I believe as a result i cannot run the pip function as well.  See image below.  I have selected "interpreter" to be Python 3.10.2 version

<img width="886" alt="image" src="https://user-images.githubusercontent.com/25963172/152537500-9a5851cb-e7ac-4f98-a1ad-1853795404d6.png">

Many thanks for your help!

Jason

**Comment by oliveruf42** [comment]
I'm new myself and I have the same problem. If you are on a Mac (which I'm guessing you are) Python 2.7 is installed by Apple when they ship the computer. If you need to use Python to deploy your script simply type Python3 deploy.py in the terminal and it should work. Or any other terminal command that requires the use of Python, just remember to type Python3

**Comment by PatrickAlphaC** [comment]
You'll want to install python3

And then use pip3 instead of pip

When running your python commands, just use `python3` instead of `python1. 

Try `pip3 --version`
