### ISSUE TITLE
could not find files for the specified model(s)

### ISSUE THREAD

**Issue by Cesarioo** [PatrickAlphaC/web3_py_simple_storage#2]
Hi 
I have an issue, whenever I execute my code this pops-up (from french, let me translate)

> could not find files for the specified model(s)

whereas it is just supposed to say nothing

![image](https://user-images.githubusercontent.com/92814105/137955629-4847414a-ab9f-46ce-a881-227a347e282d.png)

As i continue to code for now I dont believe this is serious but I would like to have an answer

Thank you so much for the hard work !!

**Comment by PatrickAlphaC** [comment]
Yep! You can ignore!
