### ISSUE TITLE
Issues installing web3

### ISSUE THREAD

**Issue by tracen80** [PatrickAlphaC/web3_py_simple_storage#22]
I installed web3 in my terminal by running pip3 install web3. It says it was successfully installed. But in VS code when I use "from web3 import web3" it says "import web3 could not be resolved"

**Comment by PatrickAlphaC** [comment]
Could you make this a stackoverflow question? Thank you!

**Comment by tracen80** [comment]
> Could you make this a stackoverflow question? Thank you!

I'm sorry I'm really new to this. I don't know what that is
