### ISSUE TITLE
Running Brownie Scripts not working ganache-cli error

### ISSUE THREAD

**Issue by kjones86** [PatrickAlphaC/web3_py_simple_storage#24]
Anyone else having trouble running `brownie run scripts/deploy.py` and then receiving a message in the terminal stating FileNotFoundError for ganache-cli? I have upgraded ganache, uninstall and reinstall and ganache-cli is still not found. However, when I run` npx ganache-cli` and `npm ganache-cli` the versions are there. I'm not sure how to resolve the error. 

<img width="1044" alt="Screen Shot 2022-02-15 at 11 30 54 PM" src="https://user-images.githubusercontent.com/90732973/154196857-c1762cfa-4ca9-43e2-867d-5e352031e5cd.png">

**Comment by PatrickAlphaC** [comment]
You need to globally install it. 

You should be able to run `ganache-cli` without `npx` or `npm`
