### ISSUE TITLE
No module named solcx

### ISSUE THREAD

**Issue by Akashbhaskar2001** [PatrickAlphaC/web3_py_simple_storage#28]
sir this is my code i tried several times and also looked into the issues and made the changes which are not in the video but still i am getting this problem pls help

from solcx import compile_standard, install_solc
with open("./SimpleStorage.sol", "r") as file:
    simple_storage_file = file.read()
print("Installing...")
install_solc("0.6.0")
compiled_sol = compile_standard(
    {
        "language": "Solidity",
        "sources": {"SimpleStorage.sol": {"content": simple_storage_file}},
        "settings": {
            "outputSelection": {
                "*": {
                    "*": ["abi", "metadata", "evm.bytecode", "evm.bytecode.sourceMap"]
                }
            }
        },
    },
    solc_version="0.6.0",
)

error : akashbhaskar@Akashs-MacBook-Air web3_py_simple_storage % python deploy.py
Traceback (most recent call last):
  File "deploy.py", line 1, in <module>
    from solcx import compile_standard, install_solc
ImportError: No module named solcx

**Comment by verystochastic** [comment]
Hi there. I am glad you posted this as I have the same error. I even copied the code from the class file in github. Did you happen to find a solution?

**Comment by PatrickAlphaC** [comment]
This has been solved here: https://github.com/smartcontractkit/full-blockchain-solidity-course-py/discussions/510

Please ask questions on the course in the main repo. Thank you!

**Comment by verystochastic** [comment]
Patrick,

Thank you so much. Really enjoying the course. Well done!
