### ISSUE TITLE
Brownie not running scripts.

### ISSUE THREAD

**Issue by Crypto-Rutvik** [PatrickAlphaC/web3_py_simple_storage#29]
Hello, I created the first project on brownie. The project compiles successfully but when I try to run script it throws error. I don't know what it is. I can't continue the course without running those. Please help.
"FileNotFoundError: [WinError 2] The system cannot find the file specified." I ensured all paths and I'm in the same directory still not working. 
![image](https://user-images.githubusercontent.com/96374993/159111459-8e6e5e74-14a9-49af-a6b5-b3691de2cd33.png)

**Comment by PatrickAlphaC** [comment]
Can you ask on the main repo? Thanks! https://github.com/smartcontractkit/full-blockchain-solidity-course-py
