### ISSUE TITLE
VS code doesn't recognize solxc

### ISSUE THREAD

**Issue by HassanSayyed** [PatrickAlphaC/web3_py_simple_storage#30]
if you are having  error at compiling solidity compiled_sol  
just write the code bellow 
  
#
    from solcx import compile_standard, install_solc

   _solc_version = "0.6.0"
    install_solc(_solc_version)

    with open("./SimpleStorage.sol", "r") as file:
     simple_storage_file = file.read()

     # Compile our solidity
     compiled_sol = compile_standard(
         {
            "language": "Solidity",
            "sources": {"SimpleStorage.sol": {"content": simple_storage_file}},
            "settings": {
                "outputSelection": {
                    "*": {"*": ["metadata", "evm.bytecode", "evm.sourceMap"]}
                }
            },
        },
        solc_version=_solc_version,
    )

    print(compiled_sol)

**Comment by oloridama** [comment]
Traceback (most recent call last):
  File "C:\Users\3\demos\web3_py_simple_storage\deploy.py", line 6, in <module>
    install_solc(_solc_version)
  File "C:\Users\3\AppData\Local\Programs\Python\Python39\lib\site-packages\solcx\install.py", line 466, in install_solc        
    raise exc
  File "C:\Users\3\AppData\Local\Programs\Python\Python39\lib\site-packages\solcx\install.py", line 459, in install_solc        
    _validate_installation(version, solcx_binary_path)
  File "C:\Users\3\AppData\Local\Programs\Python\Python39\lib\site-packages\solcx\install.py", line 636, in _validate_installation
    raise SolcInstallationError(
solcx.exceptions.SolcInstallationError: Downloaded binary would not execute, or returned unexpected output.

I keep getting this when i run the code using python deploy.py
Please help, i've been struggling with this for 3 days

**Comment by oloridama** [comment]
And I'm using windows 10, don't know if that's the problem.

**Comment by HassanSayyed** [comment]
## [py-solc-x](https://pypi.org/project/py-solc-x/)

1. Make sure you download the [library ](https://pypi.org/project/py-solc-x/)berfor you use it
       run `pip install py-solc-x`
2. Make sure you have the same code as above because it have some differences than the py-solc code used in the course
