### ISSUE TITLE
During handling of the above exception, another exception occurred

### ISSUE THREAD

**Issue by fricpto** [PatrickAlphaC/web3_py_simple_storage#35]
when I debug my web3_py_simple_storage file I get a connection error and this message "During handling of the above exception, another exception occurred"  on this line of code "nonce = w3.eth.getTransactionCount(my_address)"
<img width="641" alt="Capture" src="https://user-images.githubusercontent.com/100000316/191064008-54166412-80e1-4fc2-a36f-94942b1c8286.PNG">

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-py/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
