### ISSUE TITLE
bug on the deploy.py file

### ISSUE THREAD

**Issue by fricpto** [PatrickAlphaC/web3_py_simple_storage#36]
on this line of code "signed_txn = w3.eth.account.sign_transaction(transaction, private_key=private_key)"
Cannot convert None of type <class 'NoneType'> to bytes

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-py/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
