### ISSUE TITLE
ImportError: cannot import name 'getargspec' from 'inspect'

### ISSUE THREAD

**Issue by hoahamho** [PatrickAlphaC/web3_py_simple_storage#40]
I'm using python 3.11, window 10.
When i import Web3 from web3 and run **deploy.py**, it show me an error:  **ImportError: cannot import name 'getargspec' from 'inspect' (C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\inspect.py)**.
And can not do anything from this on, it always shown this whenever i run the **deploy.py** command.

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-py/
Thank you!
