### ISSUE TITLE
ganache-cli: command not found

### ISSUE THREAD

**Issue by sumitdevtech** [PatrickAlphaC/web3_py_simple_storage#6]
I am getting this error...after installing yarn as suggested by the instructor on my Ubuntu-20.04, but not able to figure out how to solve this even after using stackoverflow and youtube...Can anybody please help me...

**Comment by PatrickAlphaC** [comment]
Can you please check this https://ethereum.stackexchange.com/questions/92192/not-able-to-interact-with-ganache-cli-bash-ganache-cli-command-not-found

If that doesn't work, please make a stackoverflow question and then paste the link here.

**Comment by tiraspr** [comment]
Hi,
I have a similar issue with ganache-cli. I'm doing everything on Windows 10. Having successfully installed ganache using yarn, I get the error below when I run **ganache-cli --version**


ganache-cli : The term 'ganache-cli' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, 
or if a path was included, verify that the path is correct and try again.

I have looked for solutions on SO and have put the **%UserProfile%\AppData\Roaming\npm** in the Path environment variable per the SO advice. Still, the error persists.
Thanks in advance
