### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by KinuHero** [PatrickAlphaC/web3_py_simple_storage#9]
Cloned the repo and tried to deploy it, the error I get is as following:

when doing 'python deploy.py':

```
File "deploy.py", line 80
    print(f"Done! Contract deployed to {tx_receipt.contractAddress}")
                                                                   ^
SyntaxError: invalid syntax
```

**Comment by PatrickAlphaC** [comment]
Closing for now, could you add more information? What was the exact command, what information in the code did you change?

**Comment by KinuHero** [comment]
> Closing for now, could you add more information? What was the exact command, what information in the code did you change?

I just cloned the repo and ran: python deploy.py 
no changes.
